services:
  - type: web
    name: hunter-email-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: HUNTER_API_KEY
        sync: false
